
//All the Pokemon by index numbers
//MN prefix denotes a MissingNo. Pokemon
#define PKI_RHYDON        0x01
#define PKI_KANGASKAN     0x02
#define PKI_NIDORAN       0x03
#define PKI_CLEFAIRY      0x04
#define PKI_SPEAROW       0x05
#define PKI_VOLTORB       0x06
#define PKI_NIDOKING      0x07
#define PKI_SLOWBROW      0x08
#define PKI_IVYSAUR       0x09
#define PKI_EXEGGUTOR     0x0A
#define PKI_LICKITUNG     0x0B
#define PKI_EXEGGCUTE     0x0C
#define PKI_GRIMER        0x0D
#define PKI_GENGAR        0x0E
#define PKI_NIDORAN       0x0F
#define PKI_NIDOQUEEN     0x10
#define PKI_CUBONE        0x11
#define PKI_RYHORN        0x12
#define PKI_LAPRAS        0x13
#define PKI_ARCANINE      0x14
#define PKI_MEW           0x15
#define PKI_GYRADOS       0x16
#define PKI_SHELLDER      0x17
#define PKI_TENTACOOL     0x18
#define PKI_GASTLY        0x19
#define PKI_SCYTHER       0x1A
#define PKI_STARYU        0x1B
#define PKI_BLASTOISE     0x1C
#define PKI_PINSIR        0x1D
#define PKI_TANGELA       0x1E
#define PKI_MNSCIZOR      0x1F
#define PKI_MNSHUCKLE     0x20
#define PKI_GROWLITH      0x21
#define PKI_ONIX          0x22
#define PKI_FEAROW        0x23
#define PKI_PIDGEY        0x24
#define PKI_SLOWPOKE      0x25
#define PKI_KADABRA       0x26
#define PKI_GRAVELER      0x27
#define PKI_CHANSEY       0x28
#define PKI_MACHOKE       0x29
#define PKI_MRMIME        0x2A
#define PKI_HITMONLEE     0x2B
#define PKI_HITMONCHAN    0x2C
#define PKI_ARBOK         0x2D
#define PKI_PARASECT      0x2E
#define PKI_PSYDUCK       0x2F
#define PKI_DROWZEE       0x30
#define PKI_GOLEM         0x31
#define PKI_MNHERACROSS   0x32
#define PKI_MAGMAR        0x33
#define PKI_MNHOOH        0x34
#define PKI_ELECTRABUZZ   0x35
#define PKI_MAGNETON      0x36
#define PKI_KOFFING       0x37
#define PKI_MNSNEASEL     0x38
#define PKI_MANKEY        0x39
#define PKI_SEEL          0x3A
#define PKI_DIGLETT       0x3B
#define PKI_TAUROS        0x3C
#define PKI_MNTEDDIURSA   0x3D
#define PKI_MNURSARING    0x3E
#define PKI_MNSLUGMA      0x3F
#define PKI_FARFETCHD     0x40
#define PKI_VENONAT       0x41
#define PKI_DRAGONITE     0x42
#define PKI_MNMAGCARGO    0x43
#define PKI_MNSWINUB      0x44
#define PKI_MNPILOSWINE   0x45
#define PKI_DODUO         0x46
#define PKI_POLIWAG       0x47
#define PKI_JYNX          0x48
#define PKI_MOLTRES       0x49
#define PKI_ARTICUNO      0x4A
#define PKI_ZAPDOS        0x4B
#define PKI_DITTO         0x4C
#define PKI_MEOWTH        0x4D
#define PKI_KRABBY        0x4E
#define PKI_MNCORSOLA     0x4F
#define PKI_MNREMORAID    0x50
#define PKI_MNOCTILLERY   0x51
#define PKI_VULPIX        0x52
#define PKI_NINETAILS     0x53
#define PKI_PIKACHU       0x54
#define PKI_RAICHU        0x55
#define PKI_MNDELIBIRD    0x56
#define PKI_MANTINE       0x57
#define PKI_DRATINI       0x58
#define PKI_DRAGONAIR     0x59
#define PKI_KABUTO        0x5A
#define PKI_KABUTOPS      0x5B
#define PKI_HORSEA        0x5C
#define PKI_SEADRA        0x5D
#define PKI_MNSKARMORY    0x5E
#define PKI_MNHOUNDOUR    0x5F
#define PKI_SANDSHREW     0x60
#define PKI_SANDSLASH     0x61
#define PKI_OMANYTE       0x62
#define PKI_OMASTAR       0x63
#define PKI_JIGGLYPUFF    0x64
#define PKI_WIGGLYTUFF    0x65
#define PKI_EEVEE         0x66
#define PKI_FLAREON       0x67
#define PKI_JOLTEON       0x68
#define PKI_VAPOREON      0x69
#define PKI_MACHOP        0x6A
#define PKI_ZUBAT         0x6B
#define PKI_EKANS         0x6C
#define PKI_PARAS         0x6D
#define PKI_POLIWHIRL     0x6E
#define PKI_POLIWRATH     0x6F
#define PKI_WEEDLE        0x70
#define PKI_KAKUNA        0x71
#define PKI_BEEDRILL      0x72
#define PKI_MNHOUNDOOM    0x73
#define PKI_DODRIO        0x74
#define PKI_PRIMEAPE      0x75
#define PKI_DUGTRIO       0x76
#define PKI_VENOMOTH      0x77
#define PKI_DEWGONG       0x78
#define PKI_MNKINGDRA     0x79
#define PKI_MNPHANPY      0x7A
#define PKI_CATERPIE      0x7B
#define PKI_METAPOD       0x7C
#define PKI_BUTTERFREE    0x7D
#define PKI_MACHAMP       0x7E
#define PKI_MNDONPHAN     0x7F
#define PKI_GOLDUCK       0x80
#define PKI_HYPNO         0x81
#define PKI_GOLBAT        0x82
#define PKI_MEWTWO        0x83
#define PKI_SNORLAX       0x84
#define PKI_MAGIKARP      0x85
#define PKI_MNPORIGON2    0x86
#define PKI_MNSTANTLER    0x87
#define PKI_MUK           0x88
#define PKI_MNSMEARGLE    0x89
#define PKI_KINGLER       0x8A
#define PKI_CLOYSTER      0x8B
#define PKI_MNTYROGUE     0x8C
#define PKI_ELECTRODE     0x8D
#define PKI_CLEFABLE      0x8E
#define PKI_WEEZING       0x8F
#define PKI_PERSIAN       0x90
#define PKI_MAROWAK       0x91
#define PKI_MNHITMONTOP   0x92
#define PKI_HAUNTER       0x93
#define PKI_ABRA          0x94
#define PKI_ALAKAZAM      0x95
#define PKI_PIDGEOTTO     0x96
#define PKI_PIDGEOT       0x97
#define PKI_STARMIE       0x98
#define PKI_BULBASAUR     0x99
#define PKI_VENOSAUR      0x9A
#define PKI_TENTACRUEL    0x9B
#define PKI_MNSMOOCHUM    0x9C
#define PKI_GOLDEEN       0x9D
#define PKI_SEAKING       0x9E
#define PKI_MNELEKID      0x9F
#define PKI_MNMAGBY       0xA0
#define PKI_MNMILTANK     0xA1
#define PKI_MNBLISSEY     0xA2
#define PKI_PONYTA        0xA3
#define PKI_RAPIDASH      0xA4
#define PKI_RATTATA       0xA5
#define PKI_RATICATE      0xA6
#define PKI_NIDORINO      0xA7
#define PKI_NIDORINA      0xA8
#define PKI_GEODUDE       0xA9
#define PKI_PORYGON       0xAA
#define PKI_AERODACTYL    0xAB
#define PKI_RAIKOU        0xAC
#define PKI_MAGNEMITE     0xAD
#define PKI_MNENTEI       0xAE
#define PKI_MNSUICUNE     0xAF
#define PKI_CHARMANDER    0xB0
#define PKI_SQUIRTLE      0xB1
#define PKI_CHARMELEON    0xB1
#define PKI_WARTORTLE     0xB3
#define PKI_CHARIZARD     0xB4
#define PKI_MNLARVITAR    0xB5
#define PKI_MNKBTFOSSIL   0xB6
#define PKI_MNAROFOSSIL   0xB7
#define PKI_MNGHOST       0xB8
#define PKI_ODDISH        0xB9
#define PKI_GLOOM         0xBA
#define PKI_VILEPLUME     0xBB
#define PKI_BELLSPROUT    0xBC
#define PKI_WEEPINBELL    0xBD
#define PKI_VICTREEBELL   0xBE

//All the pokemon by Pokedex Number
#define PKD_BULBASAUR     1
#define PKD_IVYSAUR       2
#define PKD_VENUSAUR      3
#define PKD_CHARMANDER    4
#define PKD_CHARMELEON    5
#define PKD_CHARIZARD     6
#define PKD_SQUIRTLE      7
#define PKD_WARTORTLE     8
#define PKD_BLASTOISE     9
#define PKD_CATERPIE      10
#define PKD_METAPOD       11
#define PKD_BUTTERFREE    12
#define PKD_WEEDLE        13
#define PKD_KAKUNA        14
#define PKD_BEEDRILL      15
#define PKD_PIDGEY        16
#define PKD_PIDGEOTTO     17
#define PKD_PIDGEOT       18
#define PKD_RATTATA       19
#define PKD_RATICATE      20
#define PKD_SPEAROW       21
#define PKD_FEAROW        22
#define PKD_EKANS         23
#define PKD_ARBOK         24
#define PKD_PIKACHU       25
#define PKD_RAICHU        26
#define PKD_SANDSHREW     27
#define PKD_SANDSLASH     28
#define PKD_NIDORANF      29
#define PKD_NIDORINA      30
#define PKD_NIDOQUEEN     31
#define PKD_NIDORANM      32
#define PKD_NIDORINO      33
#define PKD_NIDOKING      34
#define PKD_CLEFAIRY      35
#define PKD_CLEFABLE      36
#define PKD_VULPIX        37
#define PKD_NINETAILS     38
#define PKD_JIGGLYPUFF    39
#define PKD_WIGGLYPUFF    40
#define PKD_ZUBAT         41
#define PKD_GOLBAT        42
#define PKD_ODDISH        43
#define PKD_GLOOM         44
#define PKD_VILEPLUME     45
#define PKD_PARAS         46
#define PKD_PARASECT      47
#define PKD_VENONAT       48
#define PKD_VENOMOTH      49
#define PKD_DIGLETT       50
#define PKD_DUGTRIO       51
#define PKD_MEOWTH        52
#define PKD_PERSIAN       53
#define PKD_PSYDUCK       54
#define PKD_GOLDUCK       55
#define PKD_MANKEY        56
#define PKD_PRIMEAPE      57
#define PKD_GROWLITHE     58
#define PKD_ARCANINE      59
#define PKD_POLIWAG       60
#define PKD_POLIWHIRL     61
#define PKD_POLIWRATH     62
#define PKD_ABRA          63
#define PKD_KADABRA       64
#define PKD_ALAKAZAM      65
#define PKD_MACHOP        66
#define PKD_MACHOKE       67
#define PKD_MACHAMP       68
#define PKD_BELLSPROUT    69
#define PKD_WEEPINBELL    70
#define PKD_VICTREEBEL    71
#define PKD_TENTACOOL     72
#define PKD_TENTACRUEL    73
#define PKD_GEODUDE       74
#define PKD_GRAVELER      75
#define PKD_GOLEM         76
#define PKD_PONYTA        77
#define PKD_RAPIDASH      78
#define PKD_SLOWPOKE      79
#define PKD_SLOWBRO       80
#define PKD_MAGNEMITE     81
#define PKD_MAGNETON      82
#define PKD_FARFETCHD     83
#define PKD_DODUO         84
#define PKD_DODRIO        85
#define PKD_SEEL          86
#define PKD_DEWGONG       87
#define PKD_GRIMER        88
#define PKD_MUK           89
#define PKD_SHELLDER      90
#define PKD_CLOYSTER      91
#define PKD_GASTLY        92
#define PKD_HAUNTER       93
#define PKD_GENGAR        94
#define PKD_ONIX          95
#define PKD_DROWZEE       96
#define PKD_HYPNO         97
#define PKD_KRABBY        98
#define PKD_KINGLER       99
#define PKD_VOLTORB       100
#define PKD_ELECTRODE     101
#define PKD_EXEGGCUTE     102
#define PKD_EXEGUTOR      103
#define PKD_CUBONE        104
#define PKD_MAROWAK       105
#define PKD_HITMONLEE     106
#define PKD_HITMONCHAN    107
#define PKD_LICKITUNG     108
#define PKD_KOFFING       109
#define PKD_WEEZING       110
#define PKD_RHYHORN       111
#define PKD_RHYDON        112
#define PKD_CHANSEY       113
#define PKD_TANGELA       114
#define PKD_KANGASKHAN    115
#define PKD_HORSEA        116
#define PKD_SEADRA        117
#define PKD_GOLDEEN       118
#define PKD_SEAKING       119
#define PKD_STARYU        120
#define PKD_STARMIE       121
#define PKD_MRMIME        122
#define PKD_SCYTHER       123
#define PKD_JYNX          124
#define PKD_ELECTRABUZZ   125
#define PKD_MAGMAR        126
#define PKD_PINSIR        127
#define PKD_TAUROS        128
#define PKD_MAGIKARP      129
#define PKD_GYARADOS      130
#define PKD_LAPRAS        131
#define PKD_DITTO         132
#define PKD_EEVEE         133
#define PKD_VAPOREON      134
#define PKD_JOLTEON       135
#define PKD_FLAREON       136
#define PKD_PORYGON       137
#define PKD_OMANYTE       138
#define PKD_OMASTAR       139
#define PKD_KABUTO        140
#define PKD_KABUTOPS      141
#define PKD_AERODATYL     142
#define PKD_SNORLAX       143
#define PKD_ARTICUNO      144
#define PKD_ZAPDOS        145
#define PKD_MOLTRES       146
#define PKD_DRATINI       147
#define PKD_DRAGONAIR     148
#define PKD_DRAGONITE     149
#define PKD_MEWTWO        150
#define PKD_MEW           151

//All the status conditions
#define STA_SLEEP       0x04
#define STA_POISON      0x08
#define STA_BURNED      0x10
#define STA_FROZEN      0x20
#define STA_PARALYZED   0x40

//All the pokemon types
#define TYP_NORMAL      0x00
#define TYP_FIGHTING    0x01
#define TYP_FLYING      0x02
#define TYP_POISON      0x03
#define TYP_GROUND      0x04
#define TYP_ROCK        0x05
#define TYP_BUG         0x07
#define TYP_GHOST       0x08
#define TYP_FIRE        0x14
#define TYP_WATER       0x15
#define TYP_GRASS       0x16
#define TYP_ELECTRIC    0x17
#define TYP_PSYCHIC     0x18
#define TYP_ICE         0x19
#define TYP_DRAGON      0x1A

//All the moves
#define MOV_POUND             1
#define MOV_KARATE_CHOP       2
#define MOV_DOUBLE_SLAP       3
#define MOV_COMET_PUNCH       4
#define MOV_MEGA_PUNCH        5
#define MOV_PAY_DAY           6
#define MOV_FIRE_PUNCH        7
#define MOV_ICE_PUNCH         8
#define MOV_THUNDER_PUNCH     9
#define MOV_SCRATCH           10
#define MOV_VICE_GRIP         11
#define MOV_GUILLOTINE        12
#define MOV_RAZOR_WIND        13
#define MOV_SWORDS_DANCE      14
#define MOV_CUT               15
#define MOV_GUST              16
#define MOV_WING_ATTACK       17
#define MOV_WHIRLWIND         18
#define MOV_FLY               19
#define MOV_BIND              20
#define MOV_SLAM              21
#define MOV_VINE_WHIP         22
#define MOV_STOMP             23
#define MOV_DOUBLE_KICK       24
#define MOV_MEGA_KICK         25
#define MOV_JUMP_KICK         26
#define MOV_ROLLING_KICK      27
#define MOV_SAND_ATTACK       28
#define MOV_HEADBUTT          29
#define MOV_HORN_ATTACK       30
#define MOV_FURY_ATTACK       31
#define MOV_HORN_DRILL        32
#define MOV_TACKLE            33
#define MOV_BODY_SLAM         34
#define MOV_WRAP              35
#define MOV_TAKE_DOWN         36
#define MOV_THRASH            37
#define MOV_DOUBLE_EDGE       38
#define MOV_TAIL_WHIP         39
#define MOV_POISON_STING      40
#define MOV_TWINEEDLE         41
#define MOV_PIN_MISSLE        42
#define MOV_LEER              43
#define MOV_BITE              44
#define MOV_GROWL             45
#define MOV_ROAR              46
#define MOV_SING              47
#define MOV_SUPERSONIC        48
#define MOV_SONIC_BOOM        49
#define MOV_DISABLE           50
#define MOV_ACID              51
#define MOV_EMBER             52
#define MOV_FLAMETHROWER      53
#define MOV_MIST              54
#define MOV_WATER_GUN         55
#define MOV_HYDRO_PUMP        56
#define MOV_SURF              57
#define MOV_ICE_BEAM          58
#define MOV_BLIZZARD          59
#define MOV_PSYBEAM           60
#define MOV_BUBBLE_BEAM       61
#define MOV_AURORA_BEAM       62
#define MOV_HYPER_BEAM        63
#define MOV_PECK              64
#define MOV_DRILL_PECK        65
#define MOV_SUBMISSION        66
#define MOV_LOW_KICK          67
#define MOV_COUNTER           68
#define MOV_SEISMIC_TOSS      69
#define MOV_STRENGTH          70
#define MOV_ABSORB            71
#define MOV_MEGA_DRAIN        72
#define MOV_LEECH_SEED        73
#define MOV_GROWTH            74
#define MOV_RAZOR_LEAF        75
#define MOV_SOLAR_BEAM        76
#define MOV_POISON_POWDER     77
#define MOV_STUN_SPORE        78
#define MOV_SLEEP_POWDER      79
#define MOV_PETAL_DANCE       80
#define MOV_STRING_SHOT       81
#define MOV_DRAGON_RAGE       82
#define MOV_FIRE_SPIN         83
#define MOV_THUNDER_SHOCK     84
#define MOV_THUNDERBOLT       85
#define MOV_THUNDER_WAVE      86
#define MOV_THUNDER           87
#define MOV_ROCK_THROW        88  
#define MOV_EARTHQUAKE        89
#define MOV_FISSURE           90
#define MOV_DIG               91
#define MOV_TOXIC             92
#define MOV_CONFUSION         93
#define MOV_PSYCHIC           94
#define MOV_HYPNOSIS          95
#define MOV_MEDITATE          96
#define MOV_AGILITY           97
#define MOV_QUICK_ATTACK      98
#define MOV_RAGE              99
#define MOV_TELEPORT          100
#define MOV_NIGHT_SHADE       101
#define MOV_MIMIC             102
#define MOV_SCREECH           103
#define MOV_DOUBLE_TEAM       104
#define MOV_RECOVER           105
#define MOV_HARDEN            106
#define MOV_MINIMIZE          107
#define MOV_SMOKESCREEN       108
#define MOV_CONFUSE_RAY       109
#define MOV_WITHDRAW          110
#define MOV_DEFENSE_CURL      111
#define MOV_BARRIER           112
#define MOV_LIGHT_SCREEN      113
#define MOV_HAZE              114
#define MOV_REFLECT           115
#define MOV_FOCUS_ENERGY      116
#define MOV_BIDE              117
#define MOV_METRONOME         118
#define MOV_MIRROR_MOVE       119
#define MOV_SELF_DESTRUCT     120
#define MOV_EGG_BOMB          121
#define MOV_LICK              122
#define MOV_SMOG              123
#define MOV_SLUDGE            124
#define MOV_BONE_CLUB         125
#define MOV_FIRE_BLAST        126
#define MOV_WATERFALL         127
#define MOV_CLAMP             128
#define MOV_SWIFT             129
#define MOV_SKULL_BASH        130
#define MOV_SPIKE_CANNON      131
#define MOV_CONSTRICT         132
#define MOV_AMNESIA           133
#define MOV_KINESIS           134
#define MOV_SOFT_BOILED       135
#define MOV_HIGH_JUMP_KICK    136
#define MOV_GLARE             137
#define MOV_DREAM_EATER       138
#define MOV_POISON_GAS        139
#define MOV_BARRAGE           140
#define MOV_LEECH_LIFE        141
#define MOV_LOVELY_KISS       142
#define MOV_SKY_ATTACK        143
#define MOV_TRANSFORM         144
#define MOV_BUBBLE            145
#define MOV_DIZZY_PUNCH       146
#define MOV_SPORE             147
#define MOV_FLASH             148
#define MOV_PSYWAVE           149
#define MOV_SPLASH            150
#define MOV_ACID_ARMOR        151
#define MOV_CRABHAMMER        152
#define MOV_EXPLOSION         153
#define MOV_FURY_SWIPES       154
#define MOV_BONEMERANG        155
#define MOV_REST              156
#define MOV_ROCK_SLIDE        157
#define MOV_HYPER_FANG        158
#define MOV_SHARPEN           159
#define MOV_CONVERSION        160
#define MOV_TRI_ATTACK        161
#define MOV_SUPER_FANG        162
#define MOV_SLASH             163
#define MOV_SUBSTITUTE        164
#define MOV_STRUGGLE          165
